export const GET_USERS = "GET_USERS"
export const GET_SINGLE_USERS = "GET_SINGLE_USERS"
export const GET_PORTFOLIO = "GET_PORTFOLIO"
export const GET_COMMERCIAL = "GET_COMMERCIAL"
export const GET_CATEGORY = "GET_CATEGORY"


